<?xml version="1.0"?>

<!DOCTYPE ebook
[
<!ELEMENT ebook (page+)>
<!ELEMENT page (topic, text, page+)>
<!ATTLIST page
          key    CDATA "auto">
<!ELEMENT topic (#PCDATA)>
<!ELEMENT text (#PCDATA)>
]>

<ebook>
	<page>
		<topic>
			Main Page
		</topic>
		<text>
			Text for the main page...
		</text>
		<page>
			<topic>
				subpage
			</topic>
			<text>
				1234456
			</text>

			<page>
				<topic>
					'nother subpage
				</topic>
				<text>
					<![CDATA[
						Here is a <A HREF="http://exml.dhs.org">link</A> to the <b>eXML</b> homepage.
					]]>			
				</text>
			</page>

		</page>	
	</page>
	<page>
		<topic>
			yet another page
		</topic>
		<text>
			... bla bla bla ...
		</text>
		<page>
			<topic>
				subpage1
			</topic>
			<text>
				... bla bla bla ...
			</text>
		</page>
		<page>
			<topic>
				subpage2
			</topic>
			<text>
				... bla bla bla ...
			</text>
		</page>
	</page>
</ebook>