<?xml version="1.0"?>

<!DOCTYPE ebook
[
<!ELEMENT ebook (page+)>
<!ELEMENT page (topic, text, page+)>
<!ATTLIST page
          key    CDATA "auto">
<!ELEMENT topic (#PCDATA)>
<!ELEMENT text (#PCDATA)>
]>

<ebook>


	<page key="index.html">
		<topic>
			About WEX
		</topic>
		<text>
			<![CDATA[
			]]>			
		</text>





		<page key="credits.html">
			<topic>
				Credits
			</topic>
			<text>
				<![CDATA[
				]]>			
			</text>
		</page>	

	</page>	





	<page key="documentation.html">
		<topic>
			Documentation
		</topic>
		<text>
			<![CDATA[
			]]>			
		</text>
	</page>





	<page key="requirements.html">
		<topic>
			Requirements
		</topic>
		<text>
			<![CDATA[
			]]>			
		</text>
	</page>








	<page key="rd.html">
		<topic>
			Release Distribution
		</topic>
		<text>
			<![CDATA[
			]]>			
		</text>


		<page key="rd_download.html">
			<topic>
				Download
			</topic>
			<text>
				<![CDATA[
				]]>			
			</text>
		</page>


	</page>


	<page key="dd.html">
		<topic>
			Developer Distribution
		</topic>
		<text>
			<![CDATA[
			]]>			
		</text>

		<page key="dd_download.html">
			<topic>
				Download
			</topic>
			<text>
				<![CDATA[
				]]>			
			</text>
		</page>


	</page>

</ebook>