=== EiffelSoftware/EiffelStudio/Delivery/dotnet/assemblies/type.dtd
<!-- type.dtd - Reflection interface Document Type Definition for XML -->


<!-- 
An Eiffel class contains three parts: header, body and footer. 
There may be no footer (if there are no invariants). 
-->
<!ELEMENT class (header, body, footer*)>

<!--
Eiffel class header begins with indexing clauses and ends with list of creation routine names.
There may be no inherit clauses (if class is not inherited).
There may be no creation routines (if class is deferred).
-->
<!ELEMENT header (modified*, frozen, expanded, deferred, generic, generic_derivations*, constraints*, class_name, alias, inherit*, create_none)>

<!-- Has class been modified? -->
<!ELEMENT modified (#PCDATA)>

<!-- Is class frozen? -->
<!ELEMENT frozen (#PCDATA)>

<!-- Is class expanded? -->
<!ELEMENT expanded (#PCDATA)>

<!-- Is class deferred? -->
<!ELEMENT deferred (#PCDATA)>

<!-- Is class generic? -->
<!ELEMENT generic (#PCDATA)>

<!-- Class generic derivations -->
<!ELEMENT generic_derivations (generic_derivation+)>

<!-- Generic derivations -->
<!ELEMENT generic_derivation (derivation_types_count, generic_type+)>

<!-- Derivation types count -->
<!ELEMENT derivation_types_count (#PCDATA)>

<!-- Generic type -->
<!ELEMENT generic_type (generic_type_eiffel_name, generic_type_external_name)>

<!-- Generic type Eiffel name -->
<!ELEMENT generic_type_eiffel_name (#PCDATA)>

<!-- Generic type .NET name -->
<!ELEMENT generic_type_external_name (#PCDATA)>

<!-- Generic type constraints -->
<!ELEMENT constraints (constraint+)>

<!-- Generic type constraint -->
<!ELEMENT constraint (#PCDATA)>

<!-- Eiffel class name -->
<!ELEMENT class_name (#PCDATA)>

<!-- 
Alias contains .NET strong name. 
There may be no public key (if assembly is not shared). 
-->
<!ELEMENT alias (simple_name, namespace*)>

<!-- .NET simple type name-->
<!ELEMENT simple_name (#PCDATA)>

<!-- Namespace defining .NET type -->
<!ELEMENT namespace (#PCDATA)>


<!-- 
Inherit clause contains class parents and possible inherit clauses 
(i.e. undefine, rename, redefine, select and export clauses).
-->
<!ELEMENT inherit (parent+)>

<!-- Inheritance clauses are related to one parent -->
<!ELEMENT parent (parent_name, undefine*, rename*, redefine*, select*, export*)>

<!-- Parent Eiffel name -->
<!ELEMENT parent_name (#PCDATA)>

<!-- List of undefine clauses -->
<!ELEMENT undefine (#PCDATA)>

<!-- List of rename clauses -->
<!ELEMENT rename (#PCDATA)>

<!-- List of redefine clauses -->
<!ELEMENT redefine (#PCDATA)>

<!-- List of select clauses -->
<!ELEMENT select (#PCDATA)>

<!-- List of export clauses -->
<!ELEMENT export (#PCDATA)>


<!-- Has class `create {NONE}' creation declaration -->
<!ELEMENT create_none (#PCDATA)>

<!--
Class body includes all features, listed by feature clauses. 
It includes neither class invariants nor end class declaration.
-->
<!ELEMENT body (initialization*, access*, element_change*, basic_operations*, unary_operators*, binary_operators*, specials*, implementation*, bit_or_infix)> 

<!-- List of features in initialization feature clause -->
<!ELEMENT initialization (feature+)>

<!-- Eiffel feature: may have arguments or not, return type or not, assertions or not. -->
<!ELEMENT feature (modified_feature*, frozen_feature, static, abstract, method, field, creation_routine, prefix, infix, new_slot, feature_eiffel_name, feature_external_name*, arguments*, return_type*, return_type_full_name*, return_type_generic_parameter_index*, comments*, preconditions*, postconditions*)>

<!-- Has feature been modified? -->
<!ELEMENT modified_feature (#PCDATA)>

<!-- Is feature frozen? -->
<!ELEMENT frozen_feature (#PCDATA)>

<!-- Is feature static? -->
<!ELEMENT static (#PCDATA)>

<!-- Is feature abstract? -->
<!ELEMENT abstract (#PCDATA)>

<!-- Is feature a method? -->
<!ELEMENT method (#PCDATA)>

<!-- Is feature a field? -->
<!ELEMENT field (#PCDATA)>

<!-- Is feature a creation routine? -->
<!ELEMENT creation_routine (#PCDATA)>

<!-- Is feature a prefix? -->
<!ELEMENT prefix (#PCDATA)>

<!-- Is feature an infix? -->
<!ELEMENT infix (#PCDATA)>

<!-- Is feature a new slot (i.e. not inherited)? -->
<!ELEMENT new_slot (#PCDATA)>

<!-- Feature Eiffel name -->
<!ELEMENT feature_eiffel_name (#PCDATA)>

<!-- Feature .NET name -->
<!ELEMENT feature_external_name (#PCDATA)>

<!-- Feature arguments. May be null. -->
<!ELEMENT arguments (argument+)>

<!-- An argument contains Eiffel name and .NET name, as well as argument type -->
<!ELEMENT argument (argument_eiffel_name*, argument_external_name*, argument_type*, argument_type_full_name*, generic_parameter_index*)>

<!-- Eiffel name of argument -->
<!ELEMENT argument_eiffel_name (#PCDATA)>

<!-- .NET name of argument -->
<!ELEMENT argument_external_name (#PCDATA)>

<!-- Eiffel name of argument type -->
<!ELEMENT argument_type (#PCDATA)>

<!-- Full name of argument type -->
<!ELEMENT argument_type_full_name (#PCDATA)>

<!-- Generic parameter index (in case the argument is generic) -->
<!ELEMENT generic_parameter_index (#PCDATA)>

<!-- Eiffel name of feature return type -->
<!ELEMENT return_type (#PCDATA)>

<!-- Full name of feature return type -->
<!ELEMENT return_type_full_name (#PCDATA)>

<!-- Return type generic parameter index (in case the return type is generic) -->
<!ELEMENT return_type_generic_parameter_index (#PCDATA)>

<!-- Feature comments -->
<!ELEMENT comments (#PCDATA)>

<!-- List of feature preconditions -->
<!ELEMENT preconditions (precondition+)>

<!-- A feature precondition contains a tag and a text -->
<!ELEMENT precondition (precondition_tag*, precondition_text)>

<!-- Precondition tag -->
<!ELEMENT precondition_tag (#PCDATA)>

<!-- Precondition text -->
<!ELEMENT precondition_text (#PCDATA)>

<!-- List of feature postconditions -->
<!ELEMENT postconditions (postcondition+)>

<!-- A feature postcondition contains a tag and a text -->
<!ELEMENT postcondition (postcondition_tag*, postcondition_text)>

<!-- Postcondition tag -->
<!ELEMENT postcondition_tag (#PCDATA)>

<!-- Postcondition text -->
<!ELEMENT postcondition_text (#PCDATA)>

<!-- List of features in access feature clause -->
<!ELEMENT access (feature+)>

<!-- List of features in element change feature clause -->
<!ELEMENT element_change (feature+)>

<!-- List of features in basic operations feature clause -->
<!ELEMENT basic_operations (feature+)>

<!-- List of features in unary operators feature clause -->
<!ELEMENT unary_operators (feature+)>

<!-- List of features in basic operations feature clause -->
<!ELEMENT binary_operators (feature+)>

<!-- List of features in specials feature clause -->
<!ELEMENT specials (feature+)>

<!-- List of features in implementation feature clause -->
<!ELEMENT implementation (feature+)>

<!-- Must a `bit_or' infix be generated? -->
<!ELEMENT bit_or_infix (#PCDATA)>

<!--
Class footer includes class invariants and end of class declaration.
May be null if no invariant.
-->
<!ELEMENT footer (invariants*)>

<!-- List of class invariants -->
<!ELEMENT invariants (invariant+)>

<!-- A class invariant contains a tag and a text -->
<!ELEMENT invariant (invariant_tag*, invariant_text)>

<!-- Invariant tag -->
<!ELEMENT invariant_tag (#PCDATA)>

<!-- Invariant text -->
<!ELEMENT invariant_text (#PCDATA)>


<!-- 
End of Document Type Definition
-->

=== EiffelSoftware/EiffelStudio/Delivery/dotnet/assemblies/mscorlib-1.0.2411.0-neutral-b77a5c561934e089/system_runtime_remoting_channels_iclientformattersink.xml
<!DOCTYPE type SYSTEM "../type.dtd">
<class>
	<header>
		<modified>False</modified>
		<frozen>False</frozen>
		<expanded>False</expanded>
		<deferred>True</deferred>
		<generic>False</generic>
		<class_eiffel_name>SYSTEM_RUNTIME_REMOTING_CHANNELS_ICLIENTFORMATTERSINK</class_eiffel_name>
		<alias>
			<simple_name>IClientFormatterSink</simple_name>
			<namespace>System.Runtime.Remoting.Channels</namespace>
			<assembly_name>mscorlib</assembly_name>
			<assembly_version>1.0.2411.0</assembly_version>
			<assembly_culture>neutral</assembly_culture>
			<assembly_public_key>b77a5c561934e089</assembly_public_key>
		</alias>
		<inherit>
			<parent>
				<parent_name>SYSTEM_RUNTIME_REMOTING_CHANNELS_ICHANNELSINKBASE</parent_name>
			</parent>
			<parent>
				<parent_name>SYSTEM_RUNTIME_REMOTING_MESSAGING_IMESSAGESINK</parent_name>
			</parent>
			<parent>
				<parent_name>SYSTEM_RUNTIME_REMOTING_CHANNELS_ICLIENTCHANNELSINK</parent_name>
			</parent>
		</inherit>
		<create_none>False</create_none>
	</header>
	<body>
		<bit_or_infix>False</bit_or_infix>
	</body>
</class>

=== EiffelSoftware/EiffelStudio/Delivery/dotnet/assemblies/System-1.0.2411.0-neutral-b77a5c561934e089/system_componentmodel_design_irootdesigner.xml
<!DOCTYPE type SYSTEM "../type.dtd">
<class>
	<header>
		<modified>False</modified>
		<frozen>False</frozen>
		<expanded>False</expanded>
		<deferred>True</deferred>
		<generic>False</generic>
		<class_eiffel_name>SYSTEM_COMPONENTMODEL_DESIGN_IROOTDESIGNER</class_eiffel_name>
		<alias>
			<simple_name>IRootDesigner</simple_name>
			<namespace>System.ComponentModel.Design</namespace>
			<assembly_name>System</assembly_name>
			<assembly_version>1.0.2411.0</assembly_version>
			<assembly_culture>neutral</assembly_culture>
			<assembly_public_key>b77a5c561934e089</assembly_public_key>
		</alias>
		<inherit>
			<parent>
				<parent_name>SYSTEM_COMPONENTMODEL_DESIGN_IDESIGNER</parent_name>
			</parent>
			<parent>
				<parent_name>SYSTEM_IDISPOSABLE</parent_name>
			</parent>
		</inherit>
		<create_none>False</create_none>
	</header>
	<body>
		<access>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>False</frozen_feature>
				<static>False</static>
				<abstract>True</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>get_supported_technologies</feature_eiffel_name>
				<feature_external_name>get_SupportedTechnologies</feature_external_name>
				<return_type>ARRAY [SYSTEM_COMPONENTMODEL_DESIGN_VIEWTECHNOLOGY]</return_type>
				<return_type_full_name>System.ComponentModel.Design.ViewTechnology[]</return_type_full_name>
			</feature>
		</access>
		<basic_operations>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>False</frozen_feature>
				<static>False</static>
				<abstract>True</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>get_view</feature_eiffel_name>
				<feature_external_name>GetView</feature_external_name>
				<arguments>
					<argument>
						<argument_eiffel_name>technology</argument_eiffel_name>
						<argument_external_name>technology</argument_external_name>
						<argument_type>SYSTEM_COMPONENTMODEL_DESIGN_VIEWTECHNOLOGY</argument_type>
						<argument_type_full_name>System.ComponentModel.Design.ViewTechnology</argument_type_full_name>
					</argument>
				</arguments>
				<return_type>ANY</return_type>
				<return_type_full_name>System.Object</return_type_full_name>
			</feature>
		</basic_operations>
		<bit_or_infix>False</bit_or_infix>
	</body>
</class>

=== EiffelSoftware/EiffelStudio/Delivery/dotnet/assemblies/System-1.0.2411.0-neutral-b77a5c561934e089/system_diagnostics_instancedatacollection.xml
<!DOCTYPE type SYSTEM "../type.dtd">
<class>
	<header>
		<modified>False</modified>
		<frozen>False</frozen>
		<expanded>False</expanded>
		<deferred>False</deferred>
		<generic>False</generic>
		<class_eiffel_name>SYSTEM_DIAGNOSTICS_INSTANCEDATACOLLECTION</class_eiffel_name>
		<alias>
			<simple_name>InstanceDataCollection</simple_name>
			<namespace>System.Diagnostics</namespace>
			<assembly_name>System</assembly_name>
			<assembly_version>1.0.2411.0</assembly_version>
			<assembly_culture>neutral</assembly_culture>
			<assembly_public_key>b77a5c561934e089</assembly_public_key>
		</alias>
		<inherit>
			<parent>
				<parent_name>SYSTEM_COLLECTIONS_IDICTIONARY</parent_name>
				<rename>get_enumerator as ienumerable_get_enumerator, remove as idictionary_remove, extend as idictionary_extend, has as idictionary_has, put_i_th as idictionary_put_i_th, get_item as idictionary_get_item, get_values as idictionary_get_values, get_sync_root as icollection_get_sync_root, get_keys as idictionary_get_keys, get_is_synchronized as icollection_get_is_synchronized, get_is_fixed_size as idictionary_get_is_fixed_size, get_is_read_only as idictionary_get_is_read_only</rename>
			</parent>
			<parent>
				<parent_name>SYSTEM_COLLECTIONS_IENUMERABLE</parent_name>
				<rename>get_enumerator as ienumerable_get_enumerator</rename>
			</parent>
			<parent>
				<parent_name>SYSTEM_COLLECTIONS_ICOLLECTION</parent_name>
				<rename>get_enumerator as ienumerable_get_enumerator, get_sync_root as icollection_get_sync_root, get_is_synchronized as icollection_get_is_synchronized</rename>
			</parent>
			<parent>
				<parent_name>SYSTEM_COLLECTIONS_DICTIONARYBASE</parent_name>
			</parent>
		</inherit>
		<create_none>False</create_none>
	</header>
	<body>
		<initialization>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>True</frozen_feature>
				<static>False</static>
				<abstract>False</abstract>
				<method>False</method>
				<field>False</field>
				<creation_routine>True</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>False</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>make_instancedatacollection</feature_eiffel_name>
				<arguments>
					<argument>
						<argument_eiffel_name>counter_name</argument_eiffel_name>
						<argument_external_name>counterName</argument_external_name>
						<argument_type>STRING</argument_type>
						<argument_type_full_name>System.String</argument_type_full_name>
					</argument>
				</arguments>
			</feature>
		</initialization>
		<access>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>True</frozen_feature>
				<static>False</static>
				<abstract>False</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>get_counter_name</feature_eiffel_name>
				<feature_external_name>get_CounterName</feature_external_name>
				<return_type>STRING</return_type>
				<return_type_full_name>System.String</return_type_full_name>
			</feature>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>True</frozen_feature>
				<static>False</static>
				<abstract>False</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>get_keys</feature_eiffel_name>
				<feature_external_name>get_Keys</feature_external_name>
				<return_type>SYSTEM_COLLECTIONS_ICOLLECTION</return_type>
				<return_type_full_name>System.Collections.ICollection</return_type_full_name>
			</feature>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>True</frozen_feature>
				<static>False</static>
				<abstract>False</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>get_values</feature_eiffel_name>
				<feature_external_name>get_Values</feature_external_name>
				<return_type>SYSTEM_COLLECTIONS_ICOLLECTION</return_type>
				<return_type_full_name>System.Collections.ICollection</return_type_full_name>
			</feature>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>True</frozen_feature>
				<static>False</static>
				<abstract>False</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>get_item</feature_eiffel_name>
				<feature_external_name>get_Item</feature_external_name>
				<arguments>
					<argument>
						<argument_eiffel_name>instance_name</argument_eiffel_name>
						<argument_external_name>instanceName</argument_external_name>
						<argument_type>STRING</argument_type>
						<argument_type_full_name>System.String</argument_type_full_name>
					</argument>
				</arguments>
				<return_type>SYSTEM_DIAGNOSTICS_INSTANCEDATA</return_type>
				<return_type_full_name>System.Diagnostics.InstanceData</return_type_full_name>
			</feature>
		</access>
		<basic_operations>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>True</frozen_feature>
				<static>False</static>
				<abstract>False</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>copy_to_array_instance_data</feature_eiffel_name>
				<feature_external_name>CopyTo</feature_external_name>
				<arguments>
					<argument>
						<argument_eiffel_name>instances</argument_eiffel_name>
						<argument_external_name>instances</argument_external_name>
						<argument_type>ARRAY [SYSTEM_DIAGNOSTICS_INSTANCEDATA]</argument_type>
						<argument_type_full_name>System.Diagnostics.InstanceData[]</argument_type_full_name>
					</argument>
					<argument>
						<argument_eiffel_name>index</argument_eiffel_name>
						<argument_external_name>index</argument_external_name>
						<argument_type>INTEGER</argument_type>
						<argument_type_full_name>System.Int32</argument_type_full_name>
					</argument>
				</arguments>
				<return_type />
				<return_type_full_name>System.Void</return_type_full_name>
			</feature>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>True</frozen_feature>
				<static>False</static>
				<abstract>False</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>has</feature_eiffel_name>
				<feature_external_name>Contains</feature_external_name>
				<arguments>
					<argument>
						<argument_eiffel_name>instance_name</argument_eiffel_name>
						<argument_external_name>instanceName</argument_external_name>
						<argument_type>STRING</argument_type>
						<argument_type_full_name>System.String</argument_type_full_name>
					</argument>
				</arguments>
				<return_type>BOOLEAN</return_type>
				<return_type_full_name>System.Boolean</return_type_full_name>
			</feature>
		</basic_operations>
		<bit_or_infix>False</bit_or_infix>
	</body>
</class>

=== EiffelSoftware/EiffelStudio/Delivery/dotnet/assemblies/mscorlib-1.0.2411.0-neutral-b77a5c561934e089/system_runtime_interopservices_ucomienumvariant.xml
<!DOCTYPE type SYSTEM "../type.dtd">
<class>
	<header>
		<modified>False</modified>
		<frozen>False</frozen>
		<expanded>False</expanded>
		<deferred>True</deferred>
		<generic>False</generic>
		<class_eiffel_name>SYSTEM_RUNTIME_INTEROPSERVICES_UCOMIENUMVARIANT</class_eiffel_name>
		<alias>
			<simple_name>UCOMIEnumVARIANT</simple_name>
			<namespace>System.Runtime.InteropServices</namespace>
			<assembly_name>mscorlib</assembly_name>
			<assembly_version>1.0.2411.0</assembly_version>
			<assembly_culture>neutral</assembly_culture>
			<assembly_public_key>b77a5c561934e089</assembly_public_key>
		</alias>
		<inherit>
			<parent>
				<parent_name>ANY</parent_name>
				<undefine>finalize, get_hash_code, equals, to_string</undefine>
			</parent>
		</inherit>
		<create_none>False</create_none>
	</header>
	<body>
		<basic_operations>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>False</frozen_feature>
				<static>False</static>
				<abstract>True</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>clone</feature_eiffel_name>
				<feature_external_name>Clone</feature_external_name>
				<arguments>
					<argument>
						<argument_eiffel_name>ppenum</argument_eiffel_name>
						<argument_external_name>ppenum</argument_external_name>
						<argument_type>INTEGER</argument_type>
						<argument_type_full_name>System.Int32</argument_type_full_name>
					</argument>
				</arguments>
				<return_type />
				<return_type_full_name>System.Void</return_type_full_name>
			</feature>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>False</frozen_feature>
				<static>False</static>
				<abstract>True</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>reset</feature_eiffel_name>
				<feature_external_name>Reset</feature_external_name>
				<return_type>INTEGER</return_type>
				<return_type_full_name>System.Int32</return_type_full_name>
			</feature>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>False</frozen_feature>
				<static>False</static>
				<abstract>True</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>skip</feature_eiffel_name>
				<feature_external_name>Skip</feature_external_name>
				<arguments>
					<argument>
						<argument_eiffel_name>celt</argument_eiffel_name>
						<argument_external_name>celt</argument_external_name>
						<argument_type>INTEGER</argument_type>
						<argument_type_full_name>System.Int32</argument_type_full_name>
					</argument>
				</arguments>
				<return_type>INTEGER</return_type>
				<return_type_full_name>System.Int32</return_type_full_name>
			</feature>
			<feature>
				<feature_modified>False</feature_modified>
				<frozen_feature>False</frozen_feature>
				<static>False</static>
				<abstract>True</abstract>
				<method>True</method>
				<field>False</field>
				<creation_routine>False</creation_routine>
				<prefix>False</prefix>
				<infix>False</infix>
				<new_slot>True</new_slot>
				<enum_literal>False</enum_literal>
				<is_literal>False</is_literal>
				<feature_eiffel_name>next</feature_eiffel_name>
				<feature_external_name>Next</feature_external_name>
				<arguments>
					<argument>
						<argument_eiffel_name>celt</argument_eiffel_name>
						<argument_external_name>celt</argument_external_name>
						<argument_type>INTEGER</argument_type>
						<argument_type_full_name>System.Int32</argument_type_full_name>
					</argument>
					<argument>
						<argument_eiffel_name>rgvar</argument_eiffel_name>
						<argument_external_name>rgvar</argument_external_name>
						<argument_type>INTEGER</argument_type>
						<argument_type_full_name>System.Int32</argument_type_full_name>
					</argument>
					<argument>
						<argument_eiffel_name>pcelt_fetched</argument_eiffel_name>
						<argument_external_name>pceltFetched</argument_external_name>
						<argument_type>INTEGER</argument_type>
						<argument_type_full_name>System.Int32</argument_type_full_name>
					</argument>
				</arguments>
				<return_type>INTEGER</return_type>
				<return_type_full_name>System.Int32</return_type_full_name>
			</feature>
		</basic_operations>
		<bit_or_infix>False</bit_or_infix>
	</body>
</class>
